ansible_user: root
ansible_ssh_common_args: -i ./keys/aiida-tutorial-master -o StrictHostKeyChecking=no
cloud_platform: hwcloud

# modify this line to switch to pyhon2
ansible_python_interpreter: /usr/bin/python3
