---
- name: Install ansible prerequisites
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: import global variables
      tags: always
      include_vars:
        file: globalconfig.yml
    - name: test global config
      debug:
        msg: RUNNING PLAYBOOK FOR '{{ vm_name }}' VERSION '{{ vm_version }}'
    - name: testing ansible environment
      debug:
        msg: Connecting to host '{{ inventory_hostname }}' as user '{{ ansible_user }}'
  roles:
    - role: marvel-nccr.ansible_prerequisites

# Note: Pass variables to roles using the 'vars' dictionary!
# If variables are passed on the same indentation level as the role, the variable is
# set correctly inside the role, but following roles will read the *default*
# value of the variable (as defined inside the role).
- name: set up the VM
  hosts: all
  vars:
    - run_tests: False
    - clean: False
    - root_user: root
  roles: 
    - name: add user {{ vm_user }} with key
      role: marvel-nccr.add_user
      vars:
        add_user_name: "{{ vm_user }}"
        add_user_public_key: "{{ lookup('file', './keys/aiida-tutorial-max.pub') }}"
        add_user_groups:
          - "{{ vm_user }}"
          - sudo
        add_user_passwordless_sudo: true
    - role: marvel-nccr.simulationbase
      tags: simulationbase
      vars:
        simulationbase_vm_user: "{{ vm_user }}"
        simulationbase_hostname: "{{ vm_hostname }}"
        simulationbase_codes_folder: "{{ vm_codes_folder }}"
    - role: marvel-nccr.ubuntu_desktop
      tags: ubuntu_desktop
      vars:
        ubuntu_desktop_browser: "{{ vm_browser }}"
        ubuntu_desktop_vm_user: "{{ vm_user }}"
      when: not vm_headless
    - role: marvel-nccr.quantum_mobile_customizations
      tags: qm_customizations
      vars:
        qm_customizations_vm_user: "{{ vm_user }}"
        qm_customizations_vm_password: "{{ vm_password }}"
        qm_customizations_vm_name: "{{ vm_name }}"
        qm_customizations_vm_version: "{{ vm_version }}"
        qm_customizations_vm_author: "{{ vm_author }}"
        qm_customizations_headless: "{{ vm_headless }}"
        qm_customizations_codes_folder: "{{ vm_codes_folder }}"
        qm_customizations_examples_folder: "{{ vm_examples_folder }}"
    - role: marvel-nccr.editors
      tags: editors
      vars:
        editors_vm_user: "{{ vm_user }}"
    - role: marvel-nccr.slurm
      tags: slurm
      vars:
        slurm_hostname: "{{ vm_hostname }}"
        slurm_cpus: "{{ vm_cpus }}"
        slurm_memory: "{{ vm_memory }}"
        slurm_hostname_service: true
    - role: marvel-nccr.quantum_espresso
      tags: quantum_espresso
    - role: marvel-nccr.yambo
      tags: yambo
    - role: marvel-nccr.fleur
      tags: fleur
    - role: marvel-nccr.siesta
      tags: siesta
    - role: marvel-nccr.cp2k
      tags: cp2k
      #vars:
      #  cp2k_installation_route: "apt"
    - role: marvel-nccr.wannier90
      tags: wannier90
    - role: marvel-nccr.aiidalab
      become: true
      become_user: "{{ vm_user }}"
      tags: aiidalab
      vars:
        aiidalab_headless: "{{ vm_headless }}"
    - role: marvel-nccr.aiida
      tags: aiida 
      become: true
      become_user: "{{ vm_user }}"
      vars:
        aiida_code_folder: "{{ vm_codes_folder }}"
        aiida_localhost_cpus: "{{ vm_cpus }}"
        aiida_examples_folder: "{{ vm_examples_folder }}"
    - role: xiamen_tutorial2019
      tags: xiamen
